image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y
  - nuget sources add -Name wasabi -Source https://www.myget.org/F/wasabi/api/v3/index.json

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:ServiceFabricPackageName="AspNetStateService-$($env:GitVersion_NuGetVersion)"
  - nuget restore
  - dotnet restore

build:
  verbosity: normal
  project: AspNetStateService.sln

after_build:
  - ps: Compress-Archive -Path "AspNetStateService.Fabric\pkg\$($env:Configuration)" -DestinationPath "$($env:ServiceFabricPackageName).zip"
  - ps: Move-Item "$($env:ServiceFabricPackageName).zip" "$($env:ServiceFabricPackageName).sfpkg"

artifacts:
  - path: $(ServiceFabricPackageName).sfpkg
    name: AspNetStateService

